FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY target/sping-all-purpose-server-0.0.1-SNAPSHOT.jar /app/sping-all-purpose-server-0.0.1-SNAPSHOT.jar
EXPOSE 8080
CMD ["java","-jar","/app/sping-all-purpose-server-0.0.1-SNAPSHOT.jar"]