
    create table client (
        id bigint generated by default as identity,
        phone varchar(32),
        first_name varchar(100) not null,
        last_name varchar(100) not null,
        email varchar(254) not null unique,
        primary key (id)
    );

    create table job (
        client_id bigint not null,
        completed_at timestamp(6) with time zone,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        location_id bigint not null,
        organization_id bigint not null,
        quote_id bigint unique,
        scheduled_at timestamp(6) with time zone,
        started_at timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        status varchar(32) not null check ((status in ('SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED'))),
        description text,
        primary key (id)
    );

    create table job_service (
        price numeric(12,2),
        quantity integer not null,
        id bigint generated by default as identity,
        job_id bigint not null,
        service_id bigint not null,
        status varchar(32) not null check ((status in ('PENDING','IN_PROGRESS','COMPLETED','SKIPPED'))),
        description text,
        primary key (id)
    );

    create table location (
        client_id bigint not null,
        id bigint generated by default as identity,
        postal_code varchar(20) not null,
        country varchar(32) not null check ((country in ('USA','CANADA'))),
        province_state varchar(100) not null,
        city varchar(120) not null,
        street varchar(200) not null,
        primary key (id),
        constraint uq_location_client_address unique (client_id, country, province_state, city, street, postal_code)
    );

    create table organization (
        active boolean not null,
        smtp_port integer,
        smtp_ssl_enabled boolean,
        smtp_starttls_enabled boolean,
        id bigint generated by default as identity,
        slug varchar(64) not null unique,
        smtp_password_env varchar(100),
        from_name varchar(150),
        name varchar(150) not null,
        contact_email varchar(254) not null,
        from_email varchar(254),
        smtp_username varchar(254),
        smtp_host varchar(255),
        primary key (id)
    );

    create table organization_service (
        organization_id bigint not null,
        service_id bigint not null,
        primary key (organization_id, service_id)
    );

    create table quote (
        client_id bigint not null,
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        location_id bigint not null,
        organization_id bigint not null,
        updated_at timestamp(6) with time zone not null,
        status varchar(32) not null check ((status in ('SUBMITTED','SENT','ACCEPTED','DECLINED','EXPIRED'))),
        description text,
        primary key (id)
    );

    create table quote_picture (
        position integer not null,
        quote_id bigint not null,
        object_key varchar(1024) not null,
        primary key (position, quote_id)
    );

    create table quote_service (
        price numeric(12,2),
        quantity integer not null,
        id bigint generated by default as identity,
        quote_id bigint not null,
        service_id bigint not null,
        description text,
        primary key (id),
        constraint uq_quote_service unique (quote_id, service_id)
    );

    create table review (
        rating integer not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        job_id bigint not null unique,
        status varchar(32) not null check ((status in ('PENDING','PUBLISHED','REJECTED'))),
        comment text,
        primary key (id)
    );

    create table service (
        active boolean not null,
        id bigint generated by default as identity,
        slug varchar(64) not null unique,
        name varchar(150) not null,
        description text,
        primary key (id)
    );

    create index ix_job_client 
       on job (client_id);

    create index ix_job_organization 
       on job (organization_id);

    create index ix_job_location 
       on job (location_id);

    create index ix_job_status 
       on job (status);

    create index ix_job_service_job 
       on job_service (job_id);

    create index ix_job_service_service 
       on job_service (service_id);

    create index ix_location_client 
       on location (client_id);

    create index ix_quote_client 
       on quote (client_id);

    create index ix_quote_organization 
       on quote (organization_id);

    create index ix_quote_location 
       on quote (location_id);

    create index ix_quote_status 
       on quote (status);

    create index ix_quote_service_quote 
       on quote_service (quote_id);

    create index ix_quote_service_service 
       on quote_service (service_id);

    alter table if exists job 
       add constraint FK17amy3r92wfc4rwxm15q4t252 
       foreign key (client_id) 
       references client;

    alter table if exists job 
       add constraint FK4d9rme1ojqlfdif4jjmmaptp1 
       foreign key (location_id) 
       references location;

    alter table if exists job 
       add constraint FK441ngnxagxwteij3weo5s4l6q 
       foreign key (organization_id) 
       references organization;

    alter table if exists job 
       add constraint FKq9vh7p1fg63txdtxxb6mbgtax 
       foreign key (quote_id) 
       references quote;

    alter table if exists job_service 
       add constraint FKh6v3mswlqq9fhwu1idjrw4ype 
       foreign key (job_id) 
       references job;

    alter table if exists job_service 
       add constraint FKq9kjqwytffbnasfcv0ab6tj2w 
       foreign key (service_id) 
       references service;

    alter table if exists location 
       add constraint FKtlwklm3ks6wa03sfliibb7o2x 
       foreign key (client_id) 
       references client;

    alter table if exists organization_service 
       add constraint FK3h9jtgtw1c4t9cvbbky4lc4y4 
       foreign key (organization_id) 
       references organization;

    alter table if exists organization_service 
       add constraint FK108kp3qr14eq2kpl9b9os91x7 
       foreign key (service_id) 
       references service;

    alter table if exists quote 
       add constraint FKau0dqte125fn24anh3k8014eu 
       foreign key (client_id) 
       references client;

    alter table if exists quote 
       add constraint FK1h1t81j40epmi5r3ucpkvd9lt 
       foreign key (location_id) 
       references location;

    alter table if exists quote 
       add constraint FKawi4ibtdbexr274vynv2qmimc 
       foreign key (organization_id) 
       references organization;

    alter table if exists quote_picture 
       add constraint FKf0858fsfwkm2t36hybeu7o187 
       foreign key (quote_id) 
       references quote;

    alter table if exists quote_service 
       add constraint FKs2sr9e4j8tniu57moei7ynv8k 
       foreign key (quote_id) 
       references quote;

    alter table if exists quote_service 
       add constraint FK6ffxgbxdno470restybo7p5kv 
       foreign key (service_id) 
       references service;

    alter table if exists review 
       add constraint FKbu0ubqxb2bkae3dfurbdj3k7j 
       foreign key (job_id) 
       references job;
