-- Baseline schema for the Organization / ServiceOffering / Quote / Job / Review model.
--
-- Column types here must match what Hibernate expects, because the application runs
-- with ddl-auto=validate. They were derived from Hibernate's own schema export for
-- these mappings; in particular Instant maps to "timestamp(6) with time zone".
--
-- Enum columns are plain varchar with no CHECK constraint on purpose: adding an enum
-- value should not require a migration. The API layer validates them.
--
-- Postgres does not create indexes for foreign keys automatically, so every FK column
-- is indexed explicitly.

-- ---------------------------------------------------------------------------
-- Catalog
-- ---------------------------------------------------------------------------

CREATE TABLE organization (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(150) NOT NULL,
    slug          VARCHAR(64)  NOT NULL,
    contact_email VARCHAR(254) NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id),
    CONSTRAINT uq_organization_slug UNIQUE (slug)
);

CREATE TABLE service (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(150) NOT NULL,
    slug        VARCHAR(64)  NOT NULL,
    description TEXT,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id),
    CONSTRAINT uq_service_slug UNIQUE (slug)
);

CREATE TABLE organization_service (
    organization_id BIGINT NOT NULL,
    service_id      BIGINT NOT NULL,
    PRIMARY KEY (organization_id, service_id),
    CONSTRAINT fk_org_service_organization FOREIGN KEY (organization_id)
        REFERENCES organization (id) ON DELETE CASCADE,
    CONSTRAINT fk_org_service_service FOREIGN KEY (service_id)
        REFERENCES service (id) ON DELETE CASCADE
);

-- The composite primary key already indexes organization_id.
CREATE INDEX ix_org_service_service ON organization_service (service_id);

-- ---------------------------------------------------------------------------
-- Client and address
-- ---------------------------------------------------------------------------

CREATE TABLE client (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(100) NOT NULL,
    last_name  VARCHAR(100) NOT NULL,
    email      VARCHAR(254) NOT NULL,
    phone      VARCHAR(32),
    PRIMARY KEY (id),
    CONSTRAINT uq_client_email UNIQUE (email)
);

-- Every column in uq_location_client_address is NOT NULL by necessity: Postgres treats
-- NULLs as distinct in a unique index, so one nullable column would silently allow the
-- duplicate address rows this constraint exists to prevent.
CREATE TABLE location (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    client_id      BIGINT       NOT NULL,
    country        VARCHAR(32)  NOT NULL,
    province_state VARCHAR(100) NOT NULL DEFAULT '',
    city           VARCHAR(120) NOT NULL,
    street         VARCHAR(200) NOT NULL,
    postal_code    VARCHAR(20)  NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_location_client FOREIGN KEY (client_id) REFERENCES client (id),
    CONSTRAINT uq_location_client_address
        UNIQUE (client_id, country, province_state, city, street, postal_code)
);

CREATE INDEX ix_location_client ON location (client_id);

-- ---------------------------------------------------------------------------
-- Quote
-- ---------------------------------------------------------------------------

CREATE TABLE quote (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    client_id       BIGINT      NOT NULL,
    organization_id BIGINT      NOT NULL,
    location_id     BIGINT      NOT NULL,
    description     TEXT,
    status          VARCHAR(32) NOT NULL,
    -- DEFAULT now() is for seed data and manual psql inserts; the application always
    -- sends an explicit value via JPA auditing.
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    expires_at      TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT fk_quote_client FOREIGN KEY (client_id) REFERENCES client (id),
    CONSTRAINT fk_quote_organization FOREIGN KEY (organization_id) REFERENCES organization (id),
    CONSTRAINT fk_quote_location FOREIGN KEY (location_id) REFERENCES location (id)
);

CREATE INDEX ix_quote_client ON quote (client_id);
CREATE INDEX ix_quote_organization ON quote (organization_id);
CREATE INDEX ix_quote_location ON quote (location_id);
CREATE INDEX ix_quote_status ON quote (status);

-- price is the unit price, not the line total; the total is computed as
-- price * quantity and never stored. Nullable because a client submits a request
-- and the organization prices it afterwards.
CREATE TABLE quote_service (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY,
    quote_id    BIGINT  NOT NULL,
    service_id  BIGINT  NOT NULL,
    price       NUMERIC(12, 2),
    quantity    INTEGER NOT NULL DEFAULT 1,
    description TEXT,
    PRIMARY KEY (id),
    CONSTRAINT fk_quote_service_quote FOREIGN KEY (quote_id)
        REFERENCES quote (id) ON DELETE CASCADE,
    CONSTRAINT fk_quote_service_service FOREIGN KEY (service_id) REFERENCES service (id),
    CONSTRAINT uq_quote_service UNIQUE (quote_id, service_id)
);

CREATE INDEX ix_quote_service_quote ON quote_service (quote_id);
CREATE INDEX ix_quote_service_service ON quote_service (service_id);

-- S3 object keys for photos attached to a quote. "position" backs the @OrderColumn
-- that makes picture order deterministic on read.
CREATE TABLE quote_picture (
    quote_id   BIGINT         NOT NULL,
    object_key VARCHAR(1024)  NOT NULL,
    position   INTEGER        NOT NULL,
    PRIMARY KEY (quote_id, position),
    CONSTRAINT fk_quote_picture_quote FOREIGN KEY (quote_id)
        REFERENCES quote (id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------
-- Job
-- ---------------------------------------------------------------------------

-- client_id / organization_id / location_id are job-level business data rather than a
-- cache of the quote's values: a job may be relocated or reassigned after quoting, and
-- nothing constrains them to keep matching the originating quote.
CREATE TABLE job (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    quote_id        BIGINT,
    client_id       BIGINT      NOT NULL,
    organization_id BIGINT      NOT NULL,
    location_id     BIGINT      NOT NULL,
    description     TEXT,
    status          VARCHAR(32) NOT NULL,
    scheduled_at    TIMESTAMP(6) WITH TIME ZONE,
    started_at      TIMESTAMP(6) WITH TIME ZONE,
    completed_at    TIMESTAMP(6) WITH TIME ZONE,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT fk_job_quote FOREIGN KEY (quote_id) REFERENCES quote (id),
    CONSTRAINT fk_job_client FOREIGN KEY (client_id) REFERENCES client (id),
    CONSTRAINT fk_job_organization FOREIGN KEY (organization_id) REFERENCES organization (id),
    CONSTRAINT fk_job_location FOREIGN KEY (location_id) REFERENCES location (id)
);

-- Partial index rather than a plain UNIQUE: it states the intent, which is that one
-- quote yields at most one job while a walk-in job may have no quote at all.
CREATE UNIQUE INDEX uq_job_quote ON job (quote_id) WHERE quote_id IS NOT NULL;

CREATE INDEX ix_job_client ON job (client_id);
CREATE INDEX ix_job_organization ON job (organization_id);
CREATE INDEX ix_job_location ON job (location_id);
CREATE INDEX ix_job_status ON job (status);

CREATE TABLE job_service (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY,
    job_id      BIGINT  NOT NULL,
    service_id  BIGINT  NOT NULL,
    price       NUMERIC(12, 2),
    quantity    INTEGER NOT NULL DEFAULT 1,
    description TEXT,
    status      VARCHAR(32) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_job_service_job FOREIGN KEY (job_id)
        REFERENCES job (id) ON DELETE CASCADE,
    CONSTRAINT fk_job_service_service FOREIGN KEY (service_id) REFERENCES service (id)
);

CREATE INDEX ix_job_service_job ON job_service (job_id);
CREATE INDEX ix_job_service_service ON job_service (service_id);

-- ---------------------------------------------------------------------------
-- Review
-- ---------------------------------------------------------------------------

CREATE TABLE review (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    job_id     BIGINT      NOT NULL,
    rating     INTEGER     NOT NULL,
    comment    TEXT,
    status     VARCHAR(32) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT fk_review_job FOREIGN KEY (job_id) REFERENCES job (id),
    CONSTRAINT uq_review_job UNIQUE (job_id),
    CONSTRAINT ck_review_rating CHECK (rating BETWEEN 1 AND 5)
);
