-- Staff accounts for the admin side of the API.
--
-- Distinct from "client": a client is someone who submitted a quote and never logs in;
-- an app_user is someone who signs in to work on those quotes. Conflating them would
-- mean every customer needed a password.
--
-- Column types match Hibernate's own export for the AppUser mapping, because the
-- application runs with ddl-auto=validate. The entity declares no explicit lengths, so
-- these are the varchar(255) defaults rather than sizes chosen here.

CREATE TABLE app_user (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    email         VARCHAR(255) NOT NULL,
    name          VARCHAR(255) NOT NULL,
    role          VARCHAR(255) NOT NULL,
    -- BCrypt output is always 60 characters; the column is wider only because the
    -- mapping does not constrain it.
    password_hash VARCHAR(255) NOT NULL,
    -- Registration creates unverified accounts, which cannot log in. Only the seeded
    -- admin starts verified, until a verification flow exists.
    verified      BOOLEAN      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id),
    CONSTRAINT uq_app_user_email UNIQUE (email)
);

-- Login looks users up by email on every attempt; the unique constraint already indexes
-- it, so no separate index is needed.
