-- Single-use email verification tokens.
--
-- A row exists only while a link is outstanding: it is deleted when the link is
-- followed, and deleted when an expired one is presented, so the table stays small
-- without a cleanup job.
--
-- ON DELETE CASCADE because a token is meaningless without its user; deleting an
-- account should not require clearing its pending links first.

CREATE TABLE email_verification (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT      NOT NULL,
    token      VARCHAR(64) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_email_verification_token UNIQUE (token),
    CONSTRAINT fk_email_verification_user FOREIGN KEY (user_id)
        REFERENCES app_user (id) ON DELETE CASCADE
);

-- Postgres does not index foreign keys automatically, and every issue-a-new-link cycle
-- looks tokens up by user to clear the previous one.
CREATE INDEX ix_email_verification_user ON email_verification (user_id);
