package com.nikita_ovramenko.sping_all_purpose_server;

import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

/**
 * A real Postgres for tests that touch the schema.
 *
 * <p>Not H2: the baseline uses GENERATED BY DEFAULT AS IDENTITY, timestamptz and a
 * partial unique index, none of which H2's Postgres compatibility mode handles
 * reliably -- and the entire point is proving the real DDL matches the real mappings.
 *
 * <p>@ServiceConnection is what points Spring at the container. Without it (or
 * @AutoConfigureTestDatabase(replace = NONE)) the test slices swap in an embedded
 * database and the tests silently prove nothing.
 *
 * <p>The container is static, so one instance is shared by every subclass.
 */
@Testcontainers
public abstract class AbstractPostgresTest {

    @Container
    @ServiceConnection
    static final PostgreSQLContainer<?> POSTGRES = new PostgreSQLContainer<>("postgres:16-alpine");
}
